##################################################################################################
# server service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-server
  labels:
    app: lab-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-server
  template:
    metadata:
      labels:
        app: lab-server
    spec:
      containers:
        - name: lab-server
          image: smmile18/lab-server:1.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: lab-server
              containerPort: 3000
